<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trdk.Geometry.NTSExtensions\Trdk.Geometry.NTS.csproj" />
    <ProjectReference Include="..\Trdk.Geometry\Trdk.Geometry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="KWRP.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
